--1.customers
CREATE TABLE rpl_customers (
    customer_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_name    VARCHAR2(100) NOT NULL,
    email            VARCHAR2(100),
    city             VARCHAR2(50),
    state            VARCHAR2(50),
    signup_date      DATE,
    customer_segment VARCHAR2(20)
);

--2.products
CREATE TABLE rpl_products (
    product_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_name     VARCHAR2(100) NOT NULL,
    category         VARCHAR2(50),
    sub_category     VARCHAR2(50),
    cost_price       NUMBER(10,2) NOT NULL,
    selling_price    NUMBER(10,2) NOT NULL,
    supplier         VARCHAR2(100)
);

--stores
CREATE TABLE rpl_stores (
    store_id         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    store_name       VARCHAR2(100) NOT NULL,
    city             VARCHAR2(50),
    state            VARCHAR2(50),
    region           VARCHAR2(50),
    store_type       VARCHAR2(30),
    opening_date     DATE
);

--4.payments
CREATE TABLE rpl_payments (
    payment_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payment_method   VARCHAR2(30),
    payment_status   VARCHAR2(20)
);

--5.orders
CREATE TABLE rpl_orders (
    order_id         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id      NUMBER NOT NULL,
    store_id         NUMBER NOT NULL,
    payment_id       NUMBER,
    order_date       DATE NOT NULL,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES rpl_customers(customer_id),
    CONSTRAINT fk_orders_store    FOREIGN KEY (store_id)    REFERENCES rpl_stores(store_id),
    CONSTRAINT fk_orders_payment  FOREIGN KEY (payment_id)  REFERENCES rpl_payments(payment_id)
);

--6.order_items
CREATE TABLE rpl_order_items (
    order_item_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id            NUMBER NOT NULL,
    product_id          NUMBER NOT NULL,
    quantity            NUMBER NOT NULL,
    unit_price          NUMBER(10,2) NOT NULL,
    discount_pct        NUMBER(5,2) DEFAULT 0,
    cost_price_at_sale  NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_items_order   FOREIGN KEY (order_id)   REFERENCES rpl_orders(order_id),
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES rpl_products(product_id)
);

--7.inventory
CREATE TABLE rpl_inventory (
    inventory_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id        NUMBER NOT NULL,
    store_id          NUMBER NOT NULL,
    stock_quantity    NUMBER NOT NULL,
    reorder_level     NUMBER DEFAULT 10,
    last_restock_date DATE,
    CONSTRAINT fk_inv_product FOREIGN KEY (product_id) REFERENCES rpl_products(product_id),
    CONSTRAINT fk_inv_store   FOREIGN KEY (store_id)   REFERENCES rpl_stores(store_id)
);

--8.returns
CREATE TABLE rpl_returns (
    return_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_item_id    NUMBER NOT NULL,
    return_date      DATE,
    return_reason    VARCHAR2(50),
    refund_amount    NUMBER(10,2),
    CONSTRAINT fk_returns_item FOREIGN KEY (order_item_id) REFERENCES rpl_order_items(order_item_id)
);

ALTER TABLE rpl_customers   MODIFY customer_id   GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE rpl_products    MODIFY product_id    GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE rpl_stores      MODIFY store_id      GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE rpl_payments    MODIFY payment_id    GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE rpl_orders      MODIFY order_id      GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE rpl_order_items MODIFY order_item_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE rpl_inventory   MODIFY inventory_id  GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE rpl_returns     MODIFY return_id     GENERATED BY DEFAULT ON NULL AS IDENTITY;



SELECT 'customers' AS tbl, COUNT(*) AS row_count FROM rpl_customers
UNION ALL SELECT 'products', COUNT(*) FROM rpl_products
UNION ALL SELECT 'stores', COUNT(*) FROM rpl_stores
UNION ALL SELECT 'payments', COUNT(*) FROM rpl_payments
UNION ALL SELECT 'orders', COUNT(*) FROM rpl_orders
UNION ALL SELECT 'order_items', COUNT(*) FROM rpl_order_items
UNION ALL SELECT 'inventory', COUNT(*) FROM rpl_inventory
UNION ALL SELECT 'returns', COUNT(*) FROM rpl_returns;

SELECT store_id, ROUND(AVG(discount_pct), 2) AS avg_discount
FROM rpl_order_items oi
JOIN rpl_orders o ON oi.order_id = o.order_id
GROUP BY store_id
ORDER BY store_id;

SELECT product_id, COUNT(*) AS times_sold
FROM rpl_order_items
WHERE product_id IN (32, 33, 34)
GROUP BY product_id;

SELECT p.category,
       COUNT(DISTINCT r.return_id) AS total_returns,
       COUNT(DISTINCT oi.order_item_id) AS total_items_sold,
       ROUND(COUNT(DISTINCT r.return_id) * 100.0 / COUNT(DISTINCT oi.order_item_id), 2) AS return_rate_pct
FROM rpl_order_items oi
JOIN rpl_products p ON oi.product_id = p.product_id
LEFT JOIN rpl_returns r ON r.order_item_id = oi.order_item_id
GROUP BY p.category
ORDER BY return_rate_pct DESC;

SELECT
    p.product_name,
    p.category,
    ROUND(SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity), 2) AS total_revenue,
    ROUND(SUM(oi.cost_price_at_sale * oi.quantity), 2) AS total_cost,
    ROUND(
        SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity)
        - SUM(oi.cost_price_at_sale * oi.quantity), 2
    ) AS total_profit,
    ROUND(
        (SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity)
         - SUM(oi.cost_price_at_sale * oi.quantity))
        / SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity) * 100, 2
    ) AS profit_margin_pct
FROM rpl_order_items oi
JOIN rpl_products p ON oi.product_id = p.product_id
GROUP BY p.product_name, p.category
ORDER BY total_revenue DESC;

WITH store_profit AS (
    SELECT
        s.store_name,
        ROUND(SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity), 2) AS total_revenue,
        ROUND(SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity) 
              - SUM(oi.cost_price_at_sale * oi.quantity), 2) AS total_profit
    FROM rpl_order_items oi
    JOIN rpl_orders o ON oi.order_id = o.order_id
    JOIN rpl_stores s ON o.store_id = s.store_id
    GROUP BY s.store_name
)
SELECT
    store_name,
    total_revenue,
    total_profit,
    rank()over(order by total_profit DESC)AS profit_rank
FROM store_profit
ORDER BY profit_rank;

SELECT
    s.store_name,
    ROUND(SUM(oi.unit_price * oi.quantity), 2) AS full_price_revenue,
    ROUND(SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity), 2) AS actual_revenue,
    ROUND(
        SUM(oi.unit_price * oi.quantity) 
        - SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity), 2
    ) AS discount_leakage,
    ROUND(
        (SUM(oi.unit_price * oi.quantity) 
         - SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity))
        / SUM(oi.unit_price * oi.quantity) * 100, 2
    ) AS discount_leakage_pct
FROM rpl_order_items oi
JOIN rpl_orders o ON oi.order_id = o.order_id
JOIN rpl_stores s ON o.store_id = s.store_id
GROUP BY s.store_name
ORDER BY discount_leakage DESC;

select rp.category,count (distinct oi.order_item_id)as total_items_sold,count (distinct r.return_id) as total_returns,
ROUND(COUNT(DISTINCT r.return_id) * 100.0 / COUNT(DISTINCT oi.order_item_id), 2) AS return_rate_pct,round(sum(r.refund_amount),2)as total_refund_loss
from rpl_order_items oi 
LEFT JOIN rpl_products rp on oi.product_id=rp.product_id
left join rpl_returns r on oi.order_item_id=r.order_item_id
group by rp.category
order by return_rate_pct desc;


select rp.product_name,sum(ri.stock_quantity)as total_stock_quantity from
rpl_inventory ri join rpl_products rp
on ri.product_id=rp.product_id
where ri.product_id not in(select product_id from rpl_order_items)
group by rp.product_name
order by total_stock_quantity;

WITH monthly_sales AS (
    SELECT
        TO_CHAR(o.order_date, 'YYYY-MM') AS sales_month,
        ROUND(SUM(oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity), 2) AS monthly_revenue
    FROM rpl_order_items oi
    JOIN rpl_orders o ON oi.order_id = o.order_id
    GROUP BY TO_CHAR(o.order_date, 'YYYY-MM')
)
SELECT
    sales_month,
    monthly_revenue,
    LAG(monthly_revenue) OVER (ORDER BY sales_month) AS prev_month_revenue,
    ROUND(
        (monthly_revenue - LAG(monthly_revenue) OVER (ORDER BY sales_month))
        / LAG(monthly_revenue) OVER (ORDER BY sales_month) * 100, 2
    ) AS growth_pct
FROM monthly_sales
ORDER BY sales_month;

WITH discount_loss AS (
    SELECT ROUND(SUM(
        oi.unit_price * oi.quantity - oi.unit_price * (1 - oi.discount_pct/100) * oi.quantity
    ), 2) AS amount
    FROM rpl_order_items oi
),
return_loss AS (
    SELECT ROUND(SUM(r.refund_amount), 2) AS amount
    FROM rpl_returns r
),
deadstock_loss AS (
    SELECT ROUND(SUM(ri.stock_quantity * rp.cost_price), 2) AS amount
    FROM rpl_inventory ri
    JOIN rpl_products rp ON ri.product_id = rp.product_id
    WHERE ri.product_id NOT IN (SELECT product_id FROM rpl_order_items)
)
SELECT 'Discount Leakage' AS leakage_type, amount FROM discount_loss
UNION ALL
SELECT 'Return Leakage', amount FROM return_loss
UNION ALL
SELECT 'Dead Stock Value', amount FROM deadstock_loss
UNION ALL
SELECT 'TOTAL LEAKAGE',
    (SELECT amount FROM discount_loss) + (SELECT amount FROM return_loss) + (SELECT amount FROM deadstock_loss)
FROM dual;